[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://agileascend.net/*"
  to = "https://hookahplus.net/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
