name: Command Launcher

on:
  workflow_dispatch:
    inputs:
      op:
        description: "switchDomain|verify|rollback"
        required: true
        type: string
      domain:
        description: "e.g., hookahplus.net"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Execute
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DNS_TOKEN: ${{ secrets.DNS_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DNS_PROVIDER: ${{ vars.DNS_PROVIDER }}
          DRY_RUN: "0"   # set to "1" for a dry run
        run: node scripts/launcher.js "${{ inputs.op }}" "${{ inputs.domain }}"
